### ISSUE TITLE
FE | Create plant-card.js functionality

### ISSUE THREAD

**Issue by emdok** [ChrisKurz098/Plantz#14]
We need to create a plant-card.js file in `public/javascript` with logic that tells the background color of the bar to change based on when it needs to be watered and when the edit button is clicked to open the Add/Edit Page.

**Acceptance criteria:**

- Create functionality that will change the color of the title bar to change color based on when it needs to be watered
- Should be three colors - green, yellow, red (check figma for hash values)
- Green means does not need to be watered
- Yellow means needs to be watered soon
- Red means it needs to be watered now
- When edit button is clicked, user is directed to the Add/Edit page with all of the fields filled out for the current plant

**Comment by ChrisKurz098** [comment]
An alternative to this feature as been added. Plant card changes color on water days
