### ISSUE TITLE
Watering Frequency Input 

### ISSUE THREAD

**Issue by cabosw** [ChrisKurz098/Plantz#53]
Currently when adding/editing plant the user inputed water frequency isn't being recognized and is replaced with a random interval.

**Comment by cabosw** [comment]
![water-frequency-bug](https://user-images.githubusercontent.com/88542124/155036268-9cfd0aa0-6536-4f6c-81b9-0641539e51b3.gif)

**Comment by emdok** [comment]
- This could have something to do with the waterFreq helper
- And we will most likely need to reappropriate the populate() function to make this appear in the select dropdowns
