### ISSUE TITLE
Plant Nickname Edit 

### ISSUE THREAD

**Issue by cabosw** [ChrisKurz098/Plantz#55]
Currently when editing the user is able to save the plant without a nickname.
Prevent user from submitting an empty field for plant nickname when editing a plant. 

We need to figure out how to make the plant nickname required in the form.

We also need to make the Date choice required in the form.

**Comment by cabosw** [comment]
<img width="1506" alt="Screen Shot 2022-02-21 at 2 40 58 PM" src="https://user-images.githubusercontent.com/88542124/155035468-f9010d25-e7fc-43ee-9ee8-8b44abf10648.png">

**Comment by emdok** [comment]
Looks like we just need to make the plant nickname required in the Form field for editing a plant.
